In [21]:
import cv2
import numpy as np

k = 100
img_num = 200
img_dim = 784

In [22]:
with open('mean.dat') as ftsf:
    mean = np.zeros(img_dim,dtype=float)
    r = 0
    for line in ftsf.readlines():
        mean_r = line.strip()
        mean[r] = float(mean_r)
        r+=1

with open('y.dat') as fy:
    y = np.zeros([k,img_num],dtype=float)
    r = 0
    for line in fy.readlines():
        y_r = line.strip().split()
        for i in range(len(y_r)):
            y[r][i] = float(y_r[i].strip())
        r+=1

with open('tsf.dat') as ftsf:
    tsf = np.zeros([k,img_dim],dtype=float)
    r = 0
    for line in ftsf.readlines():
        tsf_r = line.strip().split()
        for i in range(len(tsf_r)):
            tsf[r][i] = float(tsf_r[i].strip())
        r+=1

y = y.T
print(y)
print(tsf)

        

[[ -369.054    376.903    182.189  ...     0.         0.         0.    ]
 [-1055.45    -300.508   -261.379  ...     0.         0.         0.    ]
 [  103.945   -413.083    175.265  ...     0.         0.         0.    ]
 ...
 [  269.961    427.612   -164.749  ...     0.         0.         0.    ]
 [  -72.7894   888.379    511.319  ...     0.         0.         0.    ]
 [  -10.3898  -285.816   -196.039  ...     0.         0.         0.    ]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [23]:
x = np.matmul(y,tsf)
for i in range(img_num):
    img = (x[i] + mean).reshape((28,28))
    print(img)
    img[img<0]=0
    img[img>255]=255
    img=img.astype(np.uint8)
    cv2.imwrite('img/'+str(i)+'.png',img)


[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.000